### ISSUE TITLE
Labels of agent nodes bootstrapped by Rancherd are reverted

### ISSUE THREAD

**Issue by johnliu55tw** [rancher/rancherd#16]
We're trying to let users adding custom labels to Nodes while installing Harvester. Adding labels by modifying `/etc/rancher/rancherd/config.yaml` works just fine. However, I've observed the following behavior after Nodes rebooted:

Let's say I have a label bootstrapped by Rancherd `foo=bar`:
- For Node in `cluster-init` role, I update the label to `foo=notbar` then reboot the Node, the label would still be `foo=notbar`
- For Node in `agent` role, I update the label to `foo=notbar` then reboot the Node, the label would be reverted back to `foo=bar`.

According to issue https://github.com/rancher/rancherd/issues/4, I think `foo=bar` should only be applied once during bootstrapping? In other words, the `agent` node should have the same behavior as `cluster-init` node?

**Comment by ibuildthecloud** [comment]
Can you share the full yaml that reproduces this behavior?

**Comment by johnliu55tw** [comment]
These are the config YAML of the **agent** node. Let me know if I missed anything:

- `/etc/rancher/rancherd/config.yaml`
  ```
  server: https://192.168.122.101:8443
  role: agent
  token: 'harvester'
  kubernetesVersion: v1.21.5+rke2r1
  labels:
   - harvesterhci.io/managed=true
   - rancherd-label=installer-provided
  ```

- `/etc/rancher/rke2/config.yaml.d/40-rancherd.yaml`
  ```
  {}
  ```

- `/etc/rancher/rke2/config.yaml.d/50-rancher.yaml`
  ```
  {
    "node-label": [
      "harvesterhci.io/managed=true",
      "rancherd-label=installer-provided",
      "rke.cattle.io/machine=947a3577-7261-443c-a0fb-f8afb72955c7"
    ],
    "server": "https://192.168.122.181:9345",
    "token": "harvester"
  }
  ```

- `/etc/rancher/rke2/config.yaml.d/90-harvester-agent.yaml`
  ```
  node-label+:
   - harvesterhci.io/managed=true
  ```

Not sure if this helps, but one thing I noticed is that in the **cluster init** Node, although `/etc/rancher/rancherd/config.yaml` contains the label I want to set, but `/etc/rancher/rke2/config.yaml.d/50-rancher.yaml` doesn't have the label config:
- cluster-init Node `/etc/rancher/rke2/config.yaml.d/50-rancher.yaml`
  ```
  {
    "agent-token": "harvester",
    "cni": "calico",
    "node-label": [
      "rke.cattle.io/machine=96b24bc6-826e-463d-b97f-a40313926e1e"
    ],
    "token": "harvester"
  }
  ```

**Comment by ibuildthecloud** [comment]
@johnliu55tw The reason for this is when you assign node labels for an agent node the labels get set on the capi Machine object in Rancher.  If you don't want rancher to ensure that the node labels are set they have to be removed from the capi.Machine rke.cattle.io/labels annotations.

If you don't want the labels to persist you can try the following.  Add to `/etc/rancher/rke2/config.yaml.d/90-harvester-agent.yaml` `kubelet-arg: ["node-labels=foo=bar,foo1=bar1"]`  That should only set the node-label on create.

**Comment by johnliu55tw** [comment]
@ibuildthecloud Using `kubelet-arg` works, thanks!
