### ISSUE TITLE
Integrate Let's-Encrypt like in the other deployment methods

### ISSUE THREAD

**Issue by qdrop17** [rancher/rancherd#3]
Hi everyone.

I pretty much appreciate rancherd. It makes the provisioning of Rancher much easier. But why is Let's-Encrypt not supported by default just like the other installation methods do?

We would appreciate this a lot. Is there maybe an easy workaround to enable this?

Best qdrop

**Comment by ibuildthecloud** [comment]
@qdrop17 This repo is for a completely new implementation of rancherd.  Is your issue in reference to the existing rancherd in Rancher 2.5?  This new implementation of rancherd will support Let's Encrypt but currently is in an alpha state.

**Comment by qdrop17** [comment]
> 
> 
> @qdrop17 This repo is for a completely new implementation of rancherd. Is your issue in reference to the existing rancherd in Rancher 2.5? This new implementation of rancherd will support Let's Encrypt but currently is in an alpha state.

Yes, I followed the most recent version of the documentation: https://rancher.com/docs/rancher/v2.5/en/installation/other-installation-methods/install-rancher-on-linux/

So version v2.5.4-rc6 - but this repo is v0.0.1-alpha06. You are right - this issue is obsolete if this new release supports Let's Encrypt ;-)

**Comment by bk201** [comment]
Close because out of scope. The rancherd that the user mentioned is not this repo.
