### ISSUE TITLE
Need a way to promote an agent node to server node

### ISSUE THREAD

**Issue by bk201** [rancher/rancherd#5]
In harvester, we promote agent nodes to server nodes when the amount of total nodes are >= 3.
Currently, we are using the procedure to promote an agent node :

```
# on agent nodes
$ cat > /etc/rancher/rke2/config.yaml.d/90-harvester-server.yaml <<EOF
cni: multus,canal
disable: rke2-ingress-nginx
cluster-cidr: 10.52.0.0/16
service-cidr: 10.53.0.0/16
cluster-dns: 10.53.0.10
EOF

systemctl disable --now rke2-agent
systemctl enable --now rke2-server
```

I'm not sure if the workaround is upgrade-proof yet. It would be great that Rancherd or Rancher can provide a way to promote an agent node.

**Comment by ron1** [comment]
In your comment, did you mean `<=3`?

**Comment by guangbochen** [comment]
close as this is rke2 issue, will be tracked on https://github.com/rancher/rke2/issues/1721
