### ISSUE TITLE
v2.6.0/rancherd-amd64.tar.gz missing from release folder

### ISSUE THREAD

**Issue by dchupp** [rancher/rancherd#8]
Rancherd with defaults flags is missing files for 2.6
curl -sfL https://get.rancher.io | sh -

give this error:

[INFO]  finding release for channel latest
[INFO]  using v2.6.0 as release
[INFO]  downloading checksums at https://github.com/rancher/rancher/releases/download/v2.6.0/sha256sum.txt
[INFO]  downloading tarball at https://github.com/rancher/rancher/releases/download/v2.6.0/rancherd-amd64.tar.gz
curl: (22) The requested URL returned error: 404

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/29209#issuecomment-912078591
